### ISSUE TITLE
Update our community partners on website

### ISSUE THREAD

**Issue by awantika10** [dsclnct/Hacktoberfest-DSC-Website#11]
We don't have community partners listed on our website. Feel free to add them to the website. The following list has been given below.

- CodeMistic
- LNCT Coders Group
- Codedeck
- MLSA
- HackthisFall 2.0
- ICC Community
- Chaibiscuitblanket
- LNCT Hackathon Club
- LNCT Media Centre
- Neoteric Designers

**Comment by kamalrt11** [comment]
I would like to contribute to this issue
